---
- name: provision database
  hosts: database
  pre_tasks:
    - name: upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      sudo: yes

  roles:
    - role: ANXS.postgresql
      sudo: yes
