---
postgresql_version: 9.4
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

postgresql_client_encoding: 'UTF8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_ext_install_contrib: yes
postgresql_ext_install_dev_headers: yes
postgresql_ext_install_postgis: yes

postgresql_databases:
  - name: vagrant
    hstore: yes
    uuid_ossp: yes
    citext: yes

postgresql_users:
  - name: vagrant
    pass: dev
    encrypted: no

postgresql_user_privileges:
  - name: vagrant
    db: vagrant
    priv: "ALL"
    role_attr_flags: "SUPERUSER"

postgresql_listen_addresses:
  - 0.0.0.0

postgresql_pg_hba_custom:
  - { type: host,  database: all, user: all, address: '0.0.0.0/0',      method: 'md5', comment: 'Allow all' }
